# Generated by Django 5.2 on 2025-04-30 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='humidity',
            new_name='oxygene',
        ),
    ]
